[package]
name = "rriv_board"
version = "0.1.0"
edition = "2021"

[dependencies]
embedded-hal = "0.2.0"
one-wire-bus = "0.1.1"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

