name: Publish Firmware Binary

on:
  push:
    tags:
      - '**'

jobs:
  build:
    name: Publish binaries
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@nightly
      with:
        targets: thumbv7m-none-eabi

    - name: Cargo build
      run: cargo build --release
      working-directory: board/app
    
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: board/target/thumbv7m-none-eabi/release/app
        asset_name: rriv-firmware-${{ github.ref }}
        tag: ${{ github.ref }}
        overwrite: true
        body: "This is my release text"
    
        
