name: Verify binary builds

on:
  pull_request:
    types: [opened, reopened]
    
jobs:
  build:
    name: Verify binary builds
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@nightly
      with:
        targets: thumbv7m-none-eabi

    - name: Cargo build
      run: cargo build --release
      working-directory: board/app
    
        
